SELECT 
PH.NAME AS num_telefonico, 
IP.NAME AS ip_address, 
ICC.ICCID AS iccid, 
PI.CREATED_WHEN AS created_whem 
FROM R_OM_M2M_PI PI 
JOIN R_RI_PRIVATE_IP_ADDR IP ON PI.IP_ADDRESS = IP.OBJECT_ID 
JOIN R_RI_MOBILE_PHONE_NUMBER PH ON PI.MOBILE_PHONE_NUMBER = PH.OBJECT_ID 
JOIN R_AM_SIM ICC ON PI.SIM_CARD = ICC.OBJECT_ID 
JOIN OTC_T_ABONADOS_MOV VW ON VW.NUM_TELEFONICO = PH.NAME AND ESTADO_ABONADO <> 'BAA' 
GROUP BY PH.NAME, IP.NAME, ICC.ICCID, PI.CREATED_WHEN