--PARAMETROS PARA LA ENTIDAD D_BIRPIOTM2MTTFAPN0010
DELETE FROM params_des WHERE entidad='D_BIRPIOTM2MTTFAPN0010';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','ETAPA','1',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','VAL_RUTA','/home/nae108834/RGenerator/reportes/IOT_M2M_TRAFICO_APN',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','SHELL','/home/nae108834/RGenerator/reportes/IOT_M2M_TRAFICO_APN/bin/OTC_T_IOT_M2M_TRAFICO_APN.sh',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','VAL_DIAS_ATRAS','5',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','PARAM1_FECHA_EJEC','date_format(sysdate(),'%Y%m%d')',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','PARAM2_VAL_COLA_EJECUCION','reportes',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','PARAM3_VAL_CADENA_JDBC','jdbc:hive2://quisrvbigdata1.otecel.com.ec:2181,quisrvbigdata2.otecel.com.ec:2181,quisrvbigdata10.otecel.com.ec:2181,quisrvbigdata11.otecel.com.ec:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2?tez.queue.name=default','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','PARAM4_VAL_RUTA','/home/nae108834/RGenerator/reportes/IOT_M2M_TRAFICO_APN','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','PARAM5_VAL_USUARIO','rgenerator','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','VAL_NUM_EXECUTORS','8','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0010','VAL_NUM_EXECUTORS_CORES','4','0','0');
SELECT * FROM params_des WHERE ENTIDAD='D_BIRPIOTM2MTTFAPN0010';


--PARAMETROS PARA LA ENTIDAD D_BIRPIOTM2MTTFAPN0020
DELETE FROM params_des WHERE entidad='D_BIRPIOTM2MTTFAPN0020';
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','ETAPA','1',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_RUTA','/home/nae108834/RGenerator/reportes/IOT_M2M_TRAFICO_APN',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','SHELL','/home/nae108834/RGenerator/reportes/IOT_M2M_TRAFICO_APN/bin/OTC_T_OUT_IP.sh',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_DIAS_ATRAS','5',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','PARAM1_FECHA_EJEC','date_format(sysdate(),'%Y%m%d')',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','PARAM2_VAL_COLA_EJECUCION','reportes',0,0);
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','PARAM3_VAL_CADENA_JDBC','jdbc:hive2://quisrvbigdata1.otecel.com.ec:2181,quisrvbigdata2.otecel.com.ec:2181,quisrvbigdata10.otecel.com.ec:2181,quisrvbigdata11.otecel.com.ec:2181/;serviceDiscoveryMode=zooKeeper;zooKeeperNamespace=hiveserver2?tez.queue.name=default','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','PARAM4_VAL_RUTA','/home/nae108834/RGenerator/reportes/IOT_M2M_TRAFICO_APN','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','PARAM5_VAL_USUARIO','rgenerator','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDUSER','rdb_reportes','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDPASS','TelfEcu2017','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDHOST','proxfulldg1.otecel.com.ec','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDPORT','7594','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDDB','tomstby.otecel.com.ec','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','TDTABLE','tmp_otc_t_ip','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','HIVEDB','db_desarrollo2021','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_MASTER','yarn','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_DRIVER_MEMORY','2G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_EXECUTOR_MEMORY','4G','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_NUM_EXECUTORS','2','0','0');
INSERT INTO params_des(ENTIDAD,PARAMETRO,VALOR,ORDEN,AMBIENTE) VALUES('D_BIRPIOTM2MTTFAPN0020','VAL_EXECUTOR_CORES','2','0','0');
SELECT * FROM params_des WHERE ENTIDAD='D_BIRPIOTM2MTTFAPN0020';




